### PR TITLE
do not reserve the 15-th bit

### PR DESCRIPTION
**Pull request by nmav**
There are cases where it is used to transport TLS data

### CODE REVIEW

**Review by thomas-fossati — COMMENTED** [review]
I don't understand how that would work with the requirement in https://tools.ietf.org/html/rfc5246#section-6.2.2:
```
   If the decompression function encounters a TLSCompressed.fragment
   that would decompress to a length in excess of 2^14 bytes, it MUST
   report a fatal decompression failure error.
```
If you are right though - which is likely the case - we should also change the abstract accordingly.

**Comment by thomas-fossati** [comment]
I knew I was wrong :-) As per our offline discussion:

> I think the relevant sentence is:
> ```
> Compression must be lossless and may not increase the content length
> by more than 1024 bytes.
> ```
> My reading of it, is that you can legally have content length of 2^14, compress it and have length on the wire: 2^14+1024. Or that's my understanding of it.

Could you then fix this by changing also the Abstract and removing the Reserved Bit Considerations section altogether?

**Comment by nmav** [comment]
updated

**Review by thomas-fossati — APPROVED** [review]
thanks!

**Pull request merged**
